name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install kio dependencies
        run: pip install --upgrade -e '.[all]'
      - name: Install documentation dependencies
        run: pip install --require-hashes -r docs/requirements.txt
      - name: Build docs
        # Should use -W here to promote warnings to errors, but can't for now because of
        # a false positive for usage of _typeshed.DataclassInstance.
        run: make -C docs html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
